<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class InstrumentZacSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $instruments = [
            [
                'name' => 'Conductivímetro No.10',
                'department' => 'Calidad',
                'location' => 'Lab. Central',
                'form' => 'Instrumento Electrónico',
                'Variable Unidad De Medida' => 'Conductividad',
                'equipo' => 'Thermo Scientific Orion Star A-215',
                'brand' => 'Thermo Scientific',
                'model' => 'Orion Star A-215',
                'code' => 'X11438',
                'emt_value' => '± 100 µS/cm',
                'emt_value_decimal' => 100,
                'emt_unit' => 'µS/cm',
                'emt_symmetry' => true,
                'file_manual' => 'N/A',
            ],
            [
                'name' => 'Conductivímetro No.12',
                'department' => 'Calidad',
                'location' => 'Lab. Refinería',
                'form' => 'Instrumento Electrónico',
                'Variable Unidad De Medida' => 'Conductividad',
                'equipo' => 'Thermo Scientific Orion Star A212',
                'brand' => 'Thermo Scientific',
                'model' => 'Orion Star A212',
                'code' => 'X25472',
                'emt_value' => '± 100 µS/cm',
                'emt_value_decimal' => 100,
                'emt_unit' => 'µS/cm',
                'emt_symmetry' => true,
                'file_manual' => 'N/A',
            ],
            [
                'name' => 'Cromatógrafo de líquidos No.1',
                'department' => 'Calidad',
                'location' => 'Lab. Refinería',
                'form' => 'Instrumento Electrónico',
                'Variable Unidad De Medida' => 'Concentración',
                'equipo' => 'Cromatógrafo de líquidos No.1',
                'brand' => 'Water',
                'model' => 'Detector 2414',
                'code' => 'C12214637M',
                'emt_value' => '±0.5%',
                'emt_value_decimal' => 0.5,
                'emt_unit' => '%',
                'emt_symmetry' => true,
                'file_manual' => 'I-AC-110',
            ],
            [
                'name' => 'Cromatógrafo de líquidos No.3',
                'department' => 'Calidad',
                'location' => 'Lab. Refinería',
                'form' => 'Instrumento Electrónico',
                'Variable Unidad De Medida' => 'Concentración',
                'equipo' => 'Cromatógrafo de líquidos No.3',
                'brand' => 'Water',
                'model' => 'e2695',
                'code' => 'M10214513M-N',
                'emt_value' => '±0.5%',
                'emt_value_decimal' => 0.5,
                'emt_unit' => '%',
                'emt_symmetry' => true,
                'file_manual' => 'N/A',
            ],
            [
                'name' => 'Cromatógrafo No.2',
                'department' => 'Calidad',
                'location' => 'Lab. Refinería',
                'form' => 'Instrumento Electrónico',
                'Variable Unidad De Medida' => 'Concentración',
                'equipo' => 'Cromatógrafo No.2',
                'brand' => 'Water',
                'model' => '2414',
                'code' => 'K10214373M',
                'emt_value' => '±0.5%',
                'emt_value_decimal' => 0.5,
                'emt_unit' => '%',
                'emt_symmetry' => true,
                'file_manual' => 'I-AC-110',
            ],
            [
                'name' => 'Espectrofotómetro No.11',
                'department' => 'Calidad',
                'location' => 'Lab. Refinería',
                'form' => 'Instrumento Electrónico',
                'Variable Unidad De Medida' => 'Concentración',
                'equipo' => 'Espectrofotómetro No.11',
                'brand' => 'Thermo Scientific',
                'model' => 'Genesys 20',
                'code' => '3SGR196007',
                'emt_value' => '±1.5%',
                'emt_value_decimal' => 1.5,
                'emt_unit' => '%',
                'emt_symmetry' => true,
                'file_manual' => 'N/A',
            ],
            [
                'name' => 'Espectrofotómetro No.13',
                'department' => 'Calidad',
                'location' => 'Lab. Refinería',
                'form' => 'Instrumento Electrónico',
                'Variable Unidad De Medida' => 'Transmitancia',
                'equipo' => 'Espectrofotómetro No.13',
                'brand' => 'Perkin',
                'model' => 'Lambda 365',
                'code' => '365K7082108',
                'emt_value' => '±1.5%',
                'emt_value_decimal' => 1.5,
                'emt_unit' => '%',
                'emt_symmetry' => true,
                'file_manual' => 'N/A',
            ],
            [
                'name' => 'Luminómetro No.5',
                'department' => 'Calidad',
                'location' => 'Lab. Refinería',
                'form' => 'Instrumento Electrónico',
                'Variable Unidad De Medida' => 'MVP',
                'equipo' => 'Luminómetro No.5',
                'brand' => 'Biocontrol',
                'model' => 'Icon',
                'code' => '33180954',
                'emt_value' => 'Cal:0.5 Ver:0.4',
                'emt_value_decimal' => 0.5,
                'emt_unit' => 'MVP',
                'emt_symmetry' => false,
                'file_manual' => 'N/A',
            ],
            [
                'name' => 'Luminómetro No.6',
                'department' => 'Calidad',
                'location' => 'Lab. Refinería',
                'form' => 'Instrumento Electrónico',
                'Variable Unidad De Medida' => 'MVP',
                'equipo' => 'Luminómetro No.6',
                'brand' => 'Biocontrol',
                'model' => 'Icon',
                'code' => '29180861',
                'emt_value' => 'Cal:0.5 Ver:0.4',
                'emt_value_decimal' => 0.5,
                'emt_unit' => 'MVP',
                'emt_symmetry' => false,
                'file_manual' => 'N/A',
            ],
            [
                'name' => 'pHmetro No.6',
                'department' => 'Calidad',
                'location' => 'Lab. Refinería',
                'form' => 'Instrumento Electrónico',
                'Variable Unidad De Medida' => 'pH',
                'equipo' => 'pHmetro No.6',
                'brand' => 'Thermo Scientific',
                'model' => 'Orion Star A211',
                'code' => 'X08499',
                'emt_value' => '0.20',
                'emt_value_decimal' => 0.2,
                'emt_unit' => 'pH',
                'emt_symmetry' => false,
                'file_manual' => 'N/A',
            ],
        ];

        foreach ($instruments as $instrument) {
            DB::table('intruments')->insert([
                ...$instrument,
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        }
    }
}
